In [ ]:
from sklearn.naive_bayes import GaussianNB
import pandas as pd
from sklearn import metrics
training = pd.read_csv('/content/penguins_size - penguins_size.csv')
training

    species  culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
0    Adelie              39.1             18.7                181         3750
1    Adelie              39.5             17.4                186         3800
2    Adelie              40.3             18.0                195         3250
3    Adelie              36.7             19.3                193         3450
4    Adelie              39.3             20.6                190         3650
..      ...               ...              ...                ...          ...
337  Gentoo              47.2             13.7                214         4925
338  Gentoo              46.8             14.3                215         4850
339  Gentoo              50.4             15.7                222         5750
340  Gentoo              45.2             14.8                212         5200
341  Gentoo              49.9             16.1                213         5400

[342 rows x 5 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
x=training.drop('species',axis=1)
x

     culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
0                39.1             18.7                181         3750
1                39.5             17.4                186         3800
2                40.3             18.0                195         3250
3                36.7             19.3                193         3450
4                39.3             20.6                190         3650
..                ...              ...                ...          ...
337              47.2             13.7                214         4925
338              46.8             14.3                215         4850
339              50.4             15.7                222         5750
340              45.2             14.8                212         5200
341              49.9             16.1                213         5400

[342 rows x 4 columns]

In [ ]:
y=training['species']
y

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...
337    Gentoo
338    Gentoo
339    Gentoo
340    Gentoo
341    Gentoo
Name: species, Length: 342, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.66, random_state =100)

In [ ]:
model = GaussianNB()
model.fit(X_train, y_train)
pred = model.predict(X_train)
print(metrics.classification_report(y_train, pred))
print(metrics.confusion_matrix(y_train, pred))

              precision    recall  f1-score   support

      Adelie       0.94      0.98      0.96        52
   Chinstrap       0.95      0.87      0.91        23
      Gentoo       1.00      1.00      1.00        41

    accuracy                           0.97       116
   macro avg       0.97      0.95      0.96       116
weighted avg       0.97      0.97      0.97       116

[[51  1  0]
 [ 3 20  0]
 [ 0  0 41]]